// <auto-generated />
namespace CSResults.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddvirtualModuleinResult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddvirtualModuleinResult));
        
        string IMigrationMetadata.Id
        {
            get { return "201910131505466_Add virtual Module in Result"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
