// <auto-generated />
using System;
using CSResultsCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSResultsCore.Migrations
{
    [DbContext(typeof(ModuleContext))]
    partial class ModuleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSResultsCore.Models.Module", b =>
                {
                    b.Property<string>("moduleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("moduleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("moduleID");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("CSResultsCore.Models.Result", b =>
                {
                    b.Property<string>("moduleName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("year")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("above80")
                        .HasColumnType("float");

                    b.Property<double?>("below30")
                        .HasColumnType("float");

                    b.Property<double?>("below40")
                        .HasColumnType("float");

                    b.Property<double?>("below50")
                        .HasColumnType("float");

                    b.Property<double?>("below60")
                        .HasColumnType("float");

                    b.Property<double?>("below70")
                        .HasColumnType("float");

                    b.Property<double?>("below80")
                        .HasColumnType("float");

                    b.Property<double?>("mean")
                        .HasColumnType("float");

                    b.Property<double?>("median")
                        .HasColumnType("float");

                    b.Property<string>("moduleID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("moduleName", "year");

                    b.HasIndex("moduleID");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("CSResultsCore.Models.Result", b =>
                {
                    b.HasOne("CSResultsCore.Models.Module", "Module")
                        .WithMany("Results")
                        .HasForeignKey("moduleID");
                });
#pragma warning restore 612, 618
        }
    }
}
